### ISSUE TITLE
unimplemented get_spike_count etc.

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#107] opened 2017-09-12 01:24 UTC
In the file [https://github.com/scidash/neuronunit/blob/dev/neuronunit/capabilities/__init__.py](https://github.com/scidash/neuronunit/blob/dev/neuronunit/capabilities/__init__.py#L50-L57
)

I think that definitions with a body that consists of: `raise NotImplementedError` are methods that are meant to be inherited inside child classes (ie raise NotImplementedError is a bit the same as `pass`.

I am at a stage at the moment where I am able to pass a model around between CPUs. I have implemented `get_spike_train`, and `get_spike_count` in backend NEURON however the version of model that is passed to other CPUs is missing these class attributes/methods.

```
class ProducesSpikes(sciunit.Capability):
    """Indicates that the model produces spikes.
    No duration is required for these spikes.
    """

    def get_spike_train(self):
        """Gets computed spike times from the model.
        Arguments: None.
        Returns: a neo.core.SpikeTrain object.
        """

        raise NotImplementedError()

    def get_spike_count(self):
        spike_train = self.get_spike_train()
        return len(spike_train)


class ProducesActionPotentials(ProducesSpikes, 
                               ProducesMembranePotential):
    """Indicates the model produces action potential waveforms.
    Waveforms must have a temporal extent.
    """

    def get_APs(self):
        """Gets action potential waveform chunks from the model.
        Returns
        -------
        Must return a neo.core.AnalogSignal.
        Each column of the AnalogSignal should be a spike waveform.
        """

        raise NotImplementedError()

    def get_AP_widths(self):
        action_potentials = self.get_APs()
        widths = spikes2widths(action_potentials)
        return widths
```

**Comment by rgerkin** [comment] 2017-09-13 20:55
Duplicate of #106.

**Closed by rgerkin** 2017-09-13 20:55 UTC
