### ISSUE TITLE
After merging from scidash can't find the file where the code for score.unpickleable draws from

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#61] opened 2017-03-29 21:41 UTC
Hi @rgerkin 
After merging from scidash can't find the file where the code for score.unpickleable draws from. Was it git added?

If you scroll down to the last lines of stdout on the corresponding scidash travis build you can see the same errors: 

https://travis-ci.org/scidash/neuronunit/builds/216206049

```
jovyan@1ea5a442edd8:/home/mnt/neuronunit$ grep -r "unpicklable" *
Binary file tests/__pycache__/__init__.cpython-35.pyc matches
tests/__init__.py:        score.unpicklable.append('plot_vm')
```
.  AttributeError: 'RatioScore' object has no attribute 'unpicklable'
```
 File "analysis.py", line 108, in build_single
    score = get_neab.suite.judge(model)#passing in model, changes model
  File "/home/jovyan/work/scidash/sciunit/sciunit/__init__.py", line 430, in judge
    deep_error=deep_error)
  File "/home/jovyan/work/scidash/sciunit/sciunit/__init__.py", line 302, in judge
    raise score.score # An exception.  
  File "/home/jovyan/work/scidash/sciunit/sciunit/__init__.py", line 296, in judge
    score = self._judge(model, skip_incapable=skip_incapable)
  File "/home/jovyan/work/scidash/sciunit/sciunit/__init__.py", line 256, in _judge
    score = self._bind_score(score,model,observation,prediction)
  File "/home/jovyan/work/scidash/sciunit/sciunit/__init__.py", line 226, in _bind_score
    score = self.bind_score(score,model,observation,prediction)
  File "/home/mnt/neuronunit/tests/../../neuronunit/tests/__init__.py", line 98, in bind_score
    score.unpicklable.append('plot_vm')
AttributeError: 'RatioScore' object has no attribute 'unpicklable'
```

**Comment by rgerkin** [comment] 2017-03-29 22:09
@russelljjarvis 
It/you must not be using the newest version of SciUnit.  `unpicklable` is an attribute of every score as of yesterday.  In Travis it should be using it, since it does a normal `python setup.py install` which will use neuronunit's `setup.py` to install from the dev tarball.  For your docker instance I'm not sure, but you might want to check.

**Comment by russelljjarvis** [comment] 2017-03-29 22:25
AOK. Just noticed this update. I forgot to rebuild the Dockerfile, such that sciunit pulls from latest. Will try that now.

**Comment by russelljjarvis** [comment] 2017-03-31 00:50
After upgrading my docker build to reflect sciunit changes in scidash/sciunit +b dev:
```
  File "/opt/conda/lib/python3.5/site-packages/sciunit-0.1.5.6-py3.5.egg/sciunit/__init__.py", line 51, in __getstate__
    for key in self.unpicklable:
AttributeError: 'RheobaseTest' object has no attribute 'unpicklable'
```

**Comment by rgerkin** [comment] 2017-03-31 04:18
@russelljjarvis 
Did you rebuild the images using the `build-all` script?  If not, it might just be using the cached sciunit instead of the new one.

**Comment by rgerkin** [comment] 2017-03-31 04:21
For reference, `unpicklable` comes from [here](https://github.com/scidash/sciunit/blob/dev/sciunit/__init__.py#L43).  Every `model`, `test`, and `score` inherits from this class and calls its constructor so every model, test, and score should have this attribute *unless* you use are using a `model`, `test`, or `score` with its own constructor that doesn't call one of the parent constructors.

**Comment by rgerkin** [comment] 2017-06-30 22:02
Duplicate of #66.

**Closed by rgerkin** 2017-06-30 22:02 UTC
